/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8rOYJTK02qX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'
import { Rubik } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"
import { AccordionTrigger, AccordionContent, AccordionItem, Accordion } from "@/components/ui/accordion"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { DropdownMenuTrigger, DropdownMenuRadioItem, DropdownMenuRadioGroup, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"

export function Dash() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-white shadow-sm dark:bg-gray-950">
        <div className="container px-4 md:px-6 flex items-center justify-between h-16">
          <Link className="flex items-center gap-2" href="#">
            <MountainIcon className="h-6 w-6" />
            <span className="font-semibold text-lg">Acme Store</span>
          </Link>
          <nav className="hidden md:flex items-center gap-4">
            <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
              Home
            </Link>
            <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
              Shop
            </Link>
            <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
              About
            </Link>
            <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
              Contact
            </Link>
          </nav>
          <div className="flex items-center gap-2">
            <Button size="icon" variant="ghost">
              <SearchIcon className="w-5 h-5" />
              <span className="sr-only">Search</span>
            </Button>
            <Button size="icon" variant="ghost">
              <ShoppingCartIcon className="w-5 h-5" />
              <span className="sr-only">Cart</span>
            </Button>
            <Button size="icon" variant="ghost">
              <UserIcon className="w-5 h-5" />
              <span className="sr-only">Account</span>
            </Button>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className="bg-gray-100 dark:bg-gray-800 py-12 md:py-16 lg:py-20">
          <div className="container px-4 md:px-6">
            <Carousel
              className="w-full max-w-6xl mx-auto"
              opts={{
                align: "start",
                autoplay: true,
                interval: 5000,
                loop: true,
              }}
            >
              <CarouselContent>
                <CarouselItem>
                  <div className="grid md:grid-cols-2 gap-6 md:gap-10">
                    <img
                      alt="Featured Product"
                      className="rounded-lg object-cover w-full aspect-[3/2]"
                      height={400}
                      src="/placeholder.svg"
                      width={600}
                    />
                    <div className="flex flex-col justify-center gap-4">
                      <div className="space-y-2">
                        <div className="inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm font-medium dark:bg-gray-700 dark:text-gray-200">
                          Featured
                        </div>
                        <h2 className="text-3xl font-bold tracking-tight">Cozy Knit Sweater</h2>
                        <p className="text-gray-500 dark:text-gray-400">
                          Soft and warm knit sweater perfect for the winter season.
                        </p>
                      </div>
                      <div className="flex gap-2">
                        <Button>Add to Cart</Button>
                        <Button variant="outline">View Product</Button>
                      </div>
                    </div>
                  </div>
                </CarouselItem>
                <CarouselItem>
                  <div className="grid md:grid-cols-2 gap-6 md:gap-10">
                    <img
                      alt="Featured Product"
                      className="rounded-lg object-cover w-full aspect-[3/2]"
                      height={400}
                      src="/placeholder.svg"
                      width={600}
                    />
                    <div className="flex flex-col justify-center gap-4">
                      <div className="space-y-2">
                        <div className="inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm font-medium dark:bg-gray-700 dark:text-gray-200">
                          Featured
                        </div>
                        <h2 className="text-3xl font-bold tracking-tight">Minimalist Leather Tote</h2>
                        <p className="text-gray-500 dark:text-gray-400">
                          Elegant and durable leather tote bag for everyday use.
                        </p>
                      </div>
                      <div className="flex gap-2">
                        <Button>Add to Cart</Button>
                        <Button variant="outline">View Product</Button>
                      </div>
                    </div>
                  </div>
                </CarouselItem>
                <CarouselItem>
                  <div className="grid md:grid-cols-2 gap-6 md:gap-10">
                    <img
                      alt="Featured Product"
                      className="rounded-lg object-cover w-full aspect-[3/2]"
                      height={400}
                      src="/placeholder.svg"
                      width={600}
                    />
                    <div className="flex flex-col justify-center gap-4">
                      <div className="space-y-2">
                        <div className="inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm font-medium dark:bg-gray-700 dark:text-gray-200">
                          Featured
                        </div>
                        <h2 className="text-3xl font-bold tracking-tight">Sleek Wireless Headphones</h2>
                        <p className="text-gray-500 dark:text-gray-400">
                          High-quality wireless headphones with advanced noise cancellation.
                        </p>
                      </div>
                      <div className="flex gap-2">
                        <Button>Add to Cart</Button>
                        <Button variant="outline">View Product</Button>
                      </div>
                    </div>
                  </div>
                </CarouselItem>
              </CarouselContent>
              <CarouselPrevious className="bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 rounded-full p-2 cursor-pointer transition-colors right-20">
                <ArrowLeftIcon className="w-5 h-5 text-gray-600 dark:text-gray-400" />
              </CarouselPrevious>
              <CarouselNext />
            </Carousel>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-20">
          <div className="container px-4 md:px-6 grid md:grid-cols-[240px_1fr] gap-10 items-start">
            <div className="flex flex-col gap-4">
              <Accordion collapsible type="single">
                <AccordionItem value="category">
                  <AccordionTrigger className="text-base font-medium">Category</AccordionTrigger>
                  <AccordionContent>
                    <div className="grid gap-2">
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox />
                        Clothing
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox />
                        Accessories
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox />
                        Home & Living
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox />
                        Electronics
                      </Label>
                    </div>
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="price">
                  <AccordionTrigger className="text-base font-medium">Price</AccordionTrigger>
                  <AccordionContent>
                    <div className="grid gap-2">
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox />
                        $0 - $50
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox />
                        $50 - $100
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox />
                        $100 - $200
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox />
                        $200+
                      </Label>
                    </div>
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="color">
                  <AccordionTrigger className="text-base font-medium">Color</AccordionTrigger>
                  <AccordionContent>
                    <div className="grid gap-2">
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox />
                        Black
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox />
                        White
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox />
                        Gray
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox />
                        Blue
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox />
                        Red
                      </Label>
                    </div>
                  </AccordionContent>
                </AccordionItem>
              </Accordion>
              <Button>Apply Filters</Button>
            </div>
            <div className="grid gap-8">
              <div className="flex items-center justify-between">
                <div className="space-y-1">
                  <h2 className="text-2xl font-bold tracking-tight">Featured Products</h2>
                  <p className="text-gray-500 dark:text-gray-400">Discover our latest collection</p>
                </div>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button className="shrink-0" variant="outline">
                      <ArrowUpDownIcon className="w-4 h-4 mr-2" />
                      Sort by
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end" className="w-[200px]">
                    <DropdownMenuRadioGroup value="featured">
                      <DropdownMenuRadioItem value="featured">Featured</DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="newest">Newest</DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="low">Price: Low to High</DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="high">Price: High to Low</DropdownMenuRadioItem>
                    </DropdownMenuRadioGroup>
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
              <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
                <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
                  <Link className="absolute inset-0 z-10" href="#">
                    <span className="sr-only">View</span>
                  </Link>
                  <img
                    alt="Product"
                    className="object-cover w-full aspect-square"
                    height={300}
                    src="/placeholder.svg"
                    width={300}
                  />
                  <div className="bg-white p-4 dark:bg-gray-950">
                    <h3 className="font-bold text-lg">Cozy Knit Sweater</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">Soft and warm knit sweater</p>
                    <div className="flex items-center justify-between">
                      <span className="font-semibold text-lg">$49.99</span>
                      <Button size="icon" variant="ghost">
                        <HeartIcon className="w-5 h-5" />
                        <span className="sr-only">Add to Wishlist</span>
                      </Button>
                    </div>
                  </div>
                </div>
                <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
                  <Link className="absolute inset-0 z-10" href="#">
                    <span className="sr-only">View</span>
                  </Link>
                  <img
                    alt="Product"
                    className="object-cover w-full aspect-square"
                    height={300}
                    src="/placeholder.svg"
                    width={300}
                  />
                  <div className="bg-white p-4 dark:bg-gray-950">
                    <h3 className="font-bold text-lg">Minimalist Leather Tote</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">Elegant and durable leather tote bag</p>
                    <div className="flex items-center justify-between">
                      <span className="font-semibold text-lg">$99.99</span>
                      <Button size="icon" variant="ghost">
                        <HeartIcon className="w-5 h-5" />
                        <span className="sr-only">Add to Wishlist</span>
                      </Button>
                    </div>
                  </div>
                </div>
                <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
                  <Link className="absolute inset-0 z-10" href="#">
                    <span className="sr-only">View</span>
                  </Link>
                  <img
                    alt="Product"
                    className="object-cover w-full aspect-square"
                    height={300}
                    src="/placeholder.svg"
                    width={300}
                  />
                  <div className="bg-white p-4 dark:bg-gray-950">
                    <h3 className="font-bold text-lg">Sleek Wireless Headphones</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">High-quality wireless headphones</p>
                    <div className="flex items-center justify-between">
                      <span className="font-semibold text-lg">$149.99</span>
                      <Button size="icon" variant="ghost">
                        <HeartIcon className="w-5 h-5" />
                        <span className="sr-only">Add to Wishlist</span>
                      </Button>
                    </div>
                  </div>
                </div>
                <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
                  <Link className="absolute inset-0 z-10" href="#">
                    <span className="sr-only">View</span>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function ArrowLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  )
}


function ArrowUpDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21 16-4 4-4-4" />
      <path d="M17 20V4" />
      <path d="m3 8 4-4 4 4" />
      <path d="M7 4v16" />
    </svg>
  )
}


function HeartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
